### PR TITLE
Updates to make library work with psc 0.8.5

### PR DESCRIPTION
**Pull request by seanesss**
Hi Chris,

While trying to update your Asteroids to work with psc 0.8.5 I also had to update this library. Hope you're happy with the changes.

Sean

### CODE REVIEW

**Comment by waterson** [comment]
Sean, this is very cool... thank you! I'm a bit swamped, so give me a few days to review and merge...

**Comment by lpil** [comment]
Hi @waterson, can we merge this? :)

**Comment by waterson** [comment]
Sorry it took so long to get this done.

**Comment by lpil** [comment]
Thanks :)

**Comment by seanesss** [comment]
This still works with the latest PureScript?

**Pull request merged**
