### PR TITLE
Updated to support purs 0.11

### PR DESCRIPTION
**Pull request by adkelley**
* Supports purs 0.11.x
* Updated : 
1. tests to use purescript-dom and some components from purescript-simple-dom
2. testXX.html files to run testXX.js implicitly after window object is loaded
3. API.md to reflect decodeAudioData error handling change
* Eliminated gulp, putting new build test scripts in package.json
* Removed test files that were unrelated to purescript tests in html/

### CODE REVIEW

**Comment by waterson** [comment]
Alex, thanks for the pull request! I need to re-created my PureScript environment (it's been a while!) but I am definitely excited to look at these changes and incorporate them...

**Comment by adkelley** [comment]
Chris, it is my pleasure.  My biggest challenge was migrating the tests over, because SimpleDom.purs hasn't been upgraded to 0.11.x.  If you have any questions or comments then don’t hesitate to contact me.

**Comment by adkelley** [comment]
Hi Chris, I see this still hasn't been added to [purescript-contrib](https://github.com/purescript-contrib).  If you are busy or no longer interested in this project, then I would be pleased to take over as maintainer.  Let me know.

**Comment by newlandsvalley** [comment]
I'm really interested in this project too and would really like to help.  I've recently been trying to extend the number of audio nodes that are covered and also to develop a declarative interface into web-audio.

**Comment by waterson** [comment]
Awesome, thank you! I have added you both as collaborators; LMK if you think it would be more appropriate to do a [full-on transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/).  I just really haven't had time to keep up with PureScript these days, sigh...

**Comment by newlandsvalley** [comment]
Very many thanks, @waterson. @adkelley - I've been trying to contact you on slack to see how best to push this forward.

**Comment by adkelley** [comment]
I just responded to you on the purescript slack channel.

**Comment by adkelley** [comment]
This pull request is superseded by Ver psc update.  So I'm closing this without merging.

**Pull request closed without merging**
